name: Test Dependency Review Action

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review'
        uses: alecbuchanan/dependency-review-action@fix/vulnerability-table-duplication
        with:
          fail-on-severity: low
          allow-licenses: MIT, Apache-2.0, BSD-3-Clause
          comment-summary-in-pr: true
